version: '3.8'

services:
  lets-go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lets-go-app
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - ENV=production
    # volumes:
    #   - ./:/app  # Descomente para desenvolvimento com hot-reload